@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.anvilcraft.addon.dearpluscelestialreforge.block.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
